#!/usr/bin/env python
#Created by David Klumpenhower
#Created May 11, 2015
#Dice Number Generation Python Script

import random

diceInput = input("What type of dice are you using? d")

dice= int(diceInput)

roll = random.randrange (1, dice)

print (roll)